import { vi } from "vitest"

const Icon = () => null

vi.mock("lucide-react", () => ({
  __esModule: true,
  Activity: Icon,
  AlertCircle: Icon,
  AlertTriangle: Icon,
  Archive: Icon,
  AtSign: Icon,
  Bell: Icon,
  Bug: Icon,
  Calendar: Icon,
  Check: Icon,
  CheckCircle: Icon,
  CheckIcon: Icon,
  ChevronDown: Icon,
  ChevronLeft: Icon,
  ChevronRight: Icon,
  ChevronUp: Icon,
  ChevronsUpDown: Icon,
  Circle: Icon,
  CircleDot: Icon,
  Clock: Icon,
  Code: Icon,
  Database: Icon,
  Download: Icon,
  ExternalLink: Icon,
  Eye: Icon,
  EyeOff: Icon,
  Film: Icon,
  Filter: Icon,
  Gauge: Icon,
  GitBranch: Icon,
  GitMerge: Icon,
  HardDrive: Icon,
  Info: Icon,
  Link: Icon,
  Loader2: Icon,
  LockKeyhole: Icon,
  Moon: Icon,
  PenLine: Icon,
  Play: Icon,
  RefreshCw: Icon,
  RotateCcw: Icon,
  Save: Icon,
  Search: Icon,
  Server: Icon,
  Settings: Icon,
  Share2: Icon,
  Shield: Icon,
  ShieldAlert: Icon,
  ShieldCheck: Icon,
  ShieldEllipsis: Icon,
  Square: Icon,
  Stethoscope: Icon,
  Sun: Icon,
  Tv: Icon,
  Upload: Icon,
  Video: Icon,
  X: Icon,
  XCircle: Icon,
  Zap: Icon,
  default: Icon,
}))
