version: '3.0'
services:
  ChannelWatch:
    image: coderluii/channelwatch:latest
    container_name: channelwatch
    network_mode: host
    volumes:
      - /your/local/path:/config  # Change to your local path for config and logs
    environment:
      # ========== CORE SETTINGS ==========
      # Required: IP address of your Channels DVR server
      CHANNELS_DVR_HOST: x.x.x.x
      
      # Optional: Port for your Channels DVR server (default: 8089)
      # Only change if you've modified the default Channels DVR port
      CHANNELS_DVR_PORT: 8089
      
      # Optional: Timezone for logs and timestamps
      # Find your TZ value at: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      # Example: America/New_York, Europe/London, Asia/Tokyo
      TZ: Your/Timezone
      
      # ========== LOGGING CONFIGURATION ==========
      # Optional: Log verbosity level (1=Standard, 2=Verbose)
      LOG_LEVEL: 1
      
      # Optional: Number of days to keep log files
      LOG_RETENTION_DAYS: 7
      
      # ========== ALERT MODULES ==========
      # Enable/disable specific alert types
      # Set to TRUE to enable, FALSE to disable
      ALERT_CHANNEL_WATCHING: TRUE   # Live TV watching alerts
      ALERT_VOD_WATCHING: TRUE       # DVR/recorded content alerts
      ALERT_DISK_SPACE: TRUE         # Monitor and alert on low disk space
      ALERT_RECORDING_EVENTS: TRUE   # Recording events (scheduled, started, completed)
      
      # ========== STREAM COUNTING ==========
      # Affects BOTH channel watching AND recording alerts
      # Set TRUE to count all streams together, FALSE to disable count
      STREAM_COUNT: TRUE
      
      # ========== CHANNEL-WATCHING ALERT SETTINGS ==========
      # Control what appears in channel watching notifications
      # Set to TRUE to show, FALSE to hide
      CW_CHANNEL_NAME: TRUE       # Show channel name in notifications
      CW_CHANNEL_NUMBER: TRUE     # Show channel number in notifications
      CW_PROGRAM_NAME: TRUE       # Show program name in notifications
      CW_DEVICE_NAME: TRUE        # Show device name in notifications
      CW_DEVICE_IP: TRUE          # Show device IP address in notifications
      CW_STREAM_SOURCE: TRUE      # Show stream source in notifications
      CW_IMAGE_SOURCE: PROGRAM    # Set to "CHANNEL" or "PROGRAM" to determine which image to show
      
      # ========== RECORDING EVENTS ALERT SETTINGS ==========
      # Alert types - set to TRUE to enable, FALSE to disable
      RD_ALERT_SCHEDULED: TRUE    # Show alerts when recordings are scheduled
      RD_ALERT_STARTED: TRUE      # Show alerts when recordings start
      RD_ALERT_COMPLETED: TRUE    # Show alerts when recordings complete
      RD_ALERT_CANCELLED: TRUE    # Show alerts when recordings are cancelled
      
      # Content settings - set to TRUE to show, FALSE to hide in recording alerts
      RD_PROGRAM_NAME: TRUE       # Show program name
      RD_PROGRAM_DESC: TRUE       # Show program description
      RD_DURATION: TRUE           # Show duration
      RD_CHANNEL_NAME: TRUE       # Show channel name
      RD_CHANNEL_NUMBER: TRUE     # Show channel number
      RD_TYPE: TRUE               # Show if recording is scheduled or manual
      
      # ========== VOD WATCHING ALERT SETTINGS ==========
      # Control what appears in VOD/DVR content notifications
      VOD_TITLE: TRUE             # Show content title
      VOD_EPISODE_TITLE: TRUE     # Show episode title (for TV shows)
      VOD_SUMMARY: TRUE           # Show content summary
      VOD_DURATION: TRUE          # Show content duration
      VOD_PROGRESS: TRUE          # Show current playback progress
      VOD_IMAGE: TRUE             # Show content image
      VOD_RATING: TRUE            # Show content rating
      VOD_GENRES: TRUE            # Show content genres
      VOD_CAST: TRUE              # Show cast members
      VOD_DEVICE_NAME: TRUE       # Show device name
      VOD_DEVICE_IP: TRUE         # Show device IP
      
      # ========== CACHE SETTINGS (TTL in seconds) ==========
      CHANNEL_CACHE_TTL: 86400    # Refresh channel data every 24 hours
      PROGRAM_CACHE_TTL: 86400    # Refresh program data every 24 hours
      JOB_CACHE_TTL: 3600         # Refresh job data every hour
      VOD_CACHE_TTL: 86400        # Refresh VOD data every 24 hours
      
      # ========== DISK SPACE MONITORING ==========
      DS_THRESHOLD_PERCENT: 10  # Alert when free space falls below 10%
      DS_THRESHOLD_GB: 50       # Alert when free space falls below 50GB
      
      # ========== NOTIFICATION PROVIDERS ==========
      # Configure at least one provider below to receive alerts
      # Feel free to leave empty or completely remove any services you don't use
      
      # ----- Pushover Configuration -----
      # Get credentials at https://pushover.net
      PUSHOVER_USER_KEY: ""       # Your Pushover user key
      PUSHOVER_API_TOKEN: ""      # Your Pushover application token
      
      # ----- Apprise Configuration -----
      # Configure any services you want to use
      
      # Discord Webhooks - Format: webhook_id/webhook_token
      # Create webhook in Discord Server Settings → Integrations
      APPRISE_DISCORD: ""
      
      # Email - Format: user:password@gmail.com
      # For Gmail, use App Password from Google Account settings
      APPRISE_EMAIL: ""
      APPRISE_EMAIL_TO: ""        # Recipient email (optional)
      
      # Telegram - Format: bottoken/ChatID
      # Create bot with @BotFather and get your Chat ID with @userinfobot
      APPRISE_TELEGRAM: ""
      
      # Slack - Format: tokenA/tokenB/tokenC
      # Create app at https://api.slack.com/apps
      APPRISE_SLACK: ""
      
      # Gotify - Format: gotify.example.com/token
      # Self-hosted push notification service
      APPRISE_GOTIFY: ""
      
      # Matrix - Format: matrixuser:pass@domain/#room
      # Open-source chat platform
      APPRISE_MATRIX: ""
      
      # MQTT - Format: mqtt://user:pass@hostname
      # For smart home integrations
      APPRISE_MQTT: ""
      
      # Custom Apprise URL - For other services
      # See: https://github.com/caronc/apprise/wiki
      APPRISE_CUSTOM: ""

    restart: unless-stopped