version: '3.0'
services:
  ChannelWatch:
    image: coderluii/channelwatch:latest
    container_name: channelwatch
    network_mode: host
    volumes:
      # Path to store configuration and logs
      - /your/local/path:/config
    environment:
      # ========== CORE SETTINGS ==========
      # Required: IP address of your Channels DVR server
      CHANNELS_DVR_HOST: x.x.x.x
      
      # Optional: Port for your Channels DVR server (default: 8089)
      # Only change if you've modified the default Channels DVR port
      CHANNELS_DVR_PORT: 8089
      
      # Optional: Timezone for logs and timestamps
      # Find your TZ value at: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      # Example: America/New_York, Europe/London, Asia/Tokyo
      TZ: Your/Timezone
      
      # ========== LOGGING CONFIGURATION ==========
      # Optional: Log verbosity level (1=Standard, 2=Verbose)
      LOG_LEVEL: 1
      
      # Optional: Number of days to keep log files
      LOG_RETENTION_DAYS: 7
      
      # ========== ALERT CONFIGURATION ==========
      # Enable/disable specific alert types
      # Set to TRUE to enable, FALSE to disable (or remove the line)
      Channel-Watching: TRUE   # Live TV watching alerts
      VOD-Watching: TRUE       # DVR/recorded content alerts
      Disk-Space: TRUE         # Monitor and alert on low disk space
      
      # ========== CHANNEL-WATCHING ALERT SETTINGS ==========
      # Control what appears in channel watching notifications
      # Set to TRUE to show, FALSE to hide
      CHANNEL_NAME: TRUE       # Show channel name in notifications
      CHANNEL_NUMBER: TRUE     # Show channel number in notifications
      PROGRAM_NAME: TRUE       # Show program name in notifications
      DEVICE_NAME: TRUE        # Show device name in notifications
      DEVICE_IP_ADDRESS: TRUE  # Show device IP address in notifications
      STREAM_SOURCE: TRUE      # Show stream source in notifications
      STREAM_COUNT: TRUE       # Show total stream count in notifications
      IMAGE_SOURCE: PROGRAM    # Which image to use (CHANNEL or PROGRAM)
      
      # ========== VOD-WATCHING ALERT SETTINGS ==========
      # Control what appears in VOD/DVR content notifications
      VOD_TITLE: TRUE          # Show content title
      VOD_EPISODE_TITLE: TRUE  # Show episode title (for TV shows)
      VOD_SUMMARY: TRUE        # Show content summary
      VOD_DURATION: TRUE       # Show content duration
      VOD_PROGRESS: TRUE       # Show current playback progress
      VOD_IMAGE: TRUE          # Show content image
      VOD_RATING: TRUE         # Show content rating
      VOD_GENRES: TRUE         # Show content genres
      VOD_CAST: TRUE           # Show cast members
      VOD_DEVICE_NAME: TRUE    # Show device name
      VOD_DEVICE_IP: TRUE      # Show device IP
      
      # ========== DISK SPACE SETTINGS ==========
      # Configure disk space monitoring thresholds
      DISK_SPACE_THRESHOLD_PERCENT: 10   # Alert when free space falls below 10%
      DISK_SPACE_THRESHOLD_GB: 50        # Alert when free space falls below 50GB
      
      # ========== CACHE SETTINGS ==========
      # How long to cache data (in seconds)
      CHANNEL_CACHE_TTL: 86400     # Refresh channel data every 24 hours
      PROGRAM_CACHE_TTL: 86400     # Refresh program data every 24 hours
      VOD_CACHE_TTL: 86400         # Refresh VOD metadata every 24 hours
      
      # ========== NOTIFICATION PROVIDERS ==========
      # Configure at least one provider below to receive alerts
      # Feel free to leave empty or completely remove any services you don't use
      
      # ----- Pushover Configuration -----
      # Get credentials at https://pushover.net
      PUSHOVER_USER_KEY: ""       # Your Pushover user key
      PUSHOVER_API_TOKEN: ""      # Your Pushover application token
      
      # ----- Apprise Configuration -----
      # Configure any services you want to use
      
      # Discord Webhooks - Format: webhook_id/webhook_token
      # Create webhook in Discord Server Settings → Integrations
      APPRISE_DISCORD: ""
      
      # Email - Format: user:password@gmail.com
      # For Gmail, use App Password from Google Account settings
      APPRISE_EMAIL: ""
      APPRISE_EMAIL_TO: ""        # Recipient email (optional)
      
      # Telegram - Format: bottoken/ChatID
      # Create bot with @BotFather and get your Chat ID with @userinfobot
      APPRISE_TELEGRAM: ""
      
      # Slack - Format: tokenA/tokenB/tokenC
      # Create app at https://api.slack.com/apps
      APPRISE_SLACK: ""
      
      # Gotify - Format: gotify.example.com/token
      # Self-hosted push notification service
      APPRISE_GOTIFY: ""
      
      # Matrix - Format: matrixuser:pass@domain/#room
      # Open-source chat platform
      APPRISE_MATRIX: ""
      
      # MQTT - Format: mqtt://user:pass@hostname
      # For smart home integrations
      APPRISE_MQTT: ""
      
      # Custom Apprise URL - For other services
      # See: https://github.com/caronc/apprise/wiki
      APPRISE_CUSTOM: ""
      
    restart: unless-stopped