apiVersion: v1
kind: Secret
metadata:
  name: {{ include "channelwatch.secretName" . }}
  labels:
    {{- include "channelwatch.labels" . | nindent 4 }}
type: Opaque
stringData:
  CW_API_KEY: {{ .Values.secretConfig.apiKey | quote }}
  CW_ADMIN_USER: {{ .Values.secretConfig.adminUser | quote }}
  CW_ADMIN_PASS: {{ .Values.secretConfig.adminPass | quote }}
  CW_APPRISE_DISCORD: {{ .Values.secretConfig.appriseDiscord | quote }}
  CW_APPRISE_PUSHOVER: {{ .Values.secretConfig.apprisePushover | quote }}
  CW_APPRISE_TELEGRAM: {{ .Values.secretConfig.appriseTelegram | quote }}
  CW_APPRISE_EMAIL: {{ .Values.secretConfig.appriseEmail | quote }}
  CW_APPRISE_EMAIL_TO: {{ .Values.secretConfig.appriseEmailTo | quote }}
  CW_APPRISE_SLACK: {{ .Values.secretConfig.appriseSlack | quote }}
  CW_APPRISE_GOTIFY: {{ .Values.secretConfig.appriseGotify | quote }}
  CW_APPRISE_MATRIX: {{ .Values.secretConfig.appriseMatrix | quote }}
  CW_APPRISE_CUSTOM: {{ .Values.secretConfig.appriseCustom | quote }}
