{{- if and
      (not (.Values.secretConfig.existingSecret | trim))
      (eq (include "channelwatch.hasSecretConfig" .) "true") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "channelwatch.secretName" . }}
  labels:
    {{- include "channelwatch.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if (.Values.secretConfig.secretStorageKey | trim) }}
  CHANNELWATCH_SECRET_STORAGE_KEY: {{ .Values.secretConfig.secretStorageKey | quote }}
  {{- end }}
  {{- if (.Values.secretConfig.apiKey | trim) }}
  CW_API_KEY: {{ .Values.secretConfig.apiKey | quote }}
  {{- end }}
  {{- if (.Values.secretConfig.adminUser | trim) }}
  CW_ADMIN_USER: {{ .Values.secretConfig.adminUser | quote }}
  {{- end }}
  {{- if (.Values.secretConfig.adminPass | trim) }}
  CW_ADMIN_PASS: {{ .Values.secretConfig.adminPass | quote }}
  {{- end }}
  {{- if (.Values.secretConfig.appriseDiscord | trim) }}
  CW_APPRISE_DISCORD: {{ .Values.secretConfig.appriseDiscord | quote }}
  {{- end }}
  {{- if (.Values.secretConfig.apprisePushover | trim) }}
  CW_APPRISE_PUSHOVER: {{ .Values.secretConfig.apprisePushover | quote }}
  {{- end }}
  {{- if (.Values.secretConfig.appriseTelegram | trim) }}
  CW_APPRISE_TELEGRAM: {{ .Values.secretConfig.appriseTelegram | quote }}
  {{- end }}
  {{- if (.Values.secretConfig.appriseEmail | trim) }}
  CW_APPRISE_EMAIL: {{ .Values.secretConfig.appriseEmail | quote }}
  {{- end }}
  {{- if (.Values.secretConfig.appriseEmailTo | trim) }}
  CW_APPRISE_EMAIL_TO: {{ .Values.secretConfig.appriseEmailTo | quote }}
  {{- end }}
  {{- if (.Values.secretConfig.appriseSlack | trim) }}
  CW_APPRISE_SLACK: {{ .Values.secretConfig.appriseSlack | quote }}
  {{- end }}
  {{- if (.Values.secretConfig.appriseGotify | trim) }}
  CW_APPRISE_GOTIFY: {{ .Values.secretConfig.appriseGotify | quote }}
  {{- end }}
  {{- if (.Values.secretConfig.appriseMatrix | trim) }}
  CW_APPRISE_MATRIX: {{ .Values.secretConfig.appriseMatrix | quote }}
  {{- end }}
  {{- if (.Values.secretConfig.appriseCustom | trim) }}
  CW_APPRISE_CUSTOM: {{ .Values.secretConfig.appriseCustom | quote }}
  {{- end }}
{{- end }}
